### ISSUE TITLE
Some function Error

### ISSUE THREAD

**Issue by rezkywm** [AksaraDiskret/AksaraDiskret#19]
LOG :

`Warning: Undefined array key 0 in ..\config\functions.php on line 9`

**Comment by sariaRiski02** [comment]
Huffffhhhh. Aku i will check, i dont truth check

Pada tanggal Kam, 25 Mei 2023 19.18, Rezky Wahyudi M. <
***@***.***> menulis:

**Comment by latgit** [comment]
The same goes for signin. `Undefined variable $que in.`
