### ISSUE TITLE
Content-Length limit.

### ISSUE THREAD

**Issue by sariaRiski02** [AksaraDiskret/AksaraDiskret#22]
when you into a book to server with size file big, server output message error: 
"Warning: POST Content-Length of 67614377 bytes exceeds the limit of 41943040 bytes in Unknown on line 0.
i think the problem cause we try send so many data to server with post.
this is what I said from the start

**Comment by latgit** [comment]
Please explain in detail.

**Comment by latgit** [comment]
you can check this [POST Content-Length](https://stackoverflow.com/questions/62575437/unknown-post-content-length-exceeds-limit). But when using unlimited hosting, it doesn't matter.

**Comment by latgit** [comment]
You can check this out [POST Content-Length](https://stackoverflow.com/questions/62575437/unknown-post-content-length-exceeds-limit). But when using unlimited hosting, it doesn't matter.
