### ISSUE TITLE
edit book not uploaded a files

### ISSUE THREAD

**Issue by latgit** [AksaraDiskret/AksaraDiskret#25]
When I edit the book, only the text is replaced in the database. the files are not replaced.

**Comment by sariaRiski02** [comment]
I did use the upload function but to upload data to the "book folder" and "cover folder". then I deleted the old data in the "book folder" and "cover folder". then what is updated is only the text in the database.
for code efficiency this shouldn't be a problem.

**Comment by latgit** [comment]
> I did use the upload function but to upload data to the "book folder" and "cover folder". then I deleted the old data in the "book folder" and "cover folder". then what is updated is only the text in the database. for code efficiency this shouldn't be a problem.

I think so. Thanks.
